include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: [ build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.config.dart ]
linter:
  rules:
    - unawaited_futures
    - prefer_single_quotes
    - discarded_futures
    - prefer_relative_imports
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_escaping_inner_quotes
    - avoid_init_to_null
    - avoid_renaming_method_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_constructor_bodies
    - file_names
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_final_in_for_each
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - slash_for_doc_comments
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_super_parameters
    - void_checks
