name: car_controls
description: Allows controlling of spotify playback
publish_to: 'none'
environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_notification_listener:
    path: packages/flutter_notification_listener
  get_it: ^7.6.4
  injectable: ^2.3.0
  keep_screen_on: ^2.1.0
  logging: ^1.2.0
  spotify_sdk: 3.0.0-dev.2
  volume_controller: ^2.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-Regular.ttf
          weight: 400