name: car_controls
description: Allows controlling of spotify playback
publish_to: 'none'
environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  spotify_sdk: 3.0.0-dev.2
  injectable: ^2.3.0
  get_it: ^7.6.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - .env
